pipeline {
  agent any
  environment {
    SERVICE = "notification-service"
    PUSH_IMAGE = "kind-registry:5000/${SERVICE}"
    DEPLOY_IMAGE = "localhost:5051/${SERVICE}"
    TAG = "${env.GIT_COMMIT.take(7)}"
  }
  stages {
    stage('Install') {
      steps { sh 'npm install' }
    }
    stage('Build Image') {
      steps { sh "docker build -t ${PUSH_IMAGE}:${TAG} -t ${PUSH_IMAGE}:latest ." }
    }
    stage('Push to local registry') {
      steps {
        sh "docker push ${PUSH_IMAGE}:${TAG}"
        sh "docker push ${PUSH_IMAGE}:latest"
      }
    }
    stage('Bump image tag in git (GitOps)') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'github-pat', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_TOKEN')]) {
          sh """
            cd \$WORKSPACE
            sed -i.bak "s#${DEPLOY_IMAGE}:.*#${DEPLOY_IMAGE}:${TAG}#" infra/k8s/base/notification-service/deployment.yaml
            git config user.email "jenkins@mintoak-project.local"
            git config user.name "jenkins"
            git add infra/k8s/base/notification-service/deployment.yaml
            git commit -m "ci: bump notification-service image to ${TAG}" || echo "nothing to commit"
            git push https://${GIT_USER}:${GIT_TOKEN}@github.com/chavanakash/mintoak-project.git HEAD:main
          """
        }
      }
    }
  }
}
