apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mintoak-notification-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/chavanakash/mintoak-project.git # <-- change me
    targetRevision: main
    path: infra/k8s/base/notification-service
  destination:
    server: https://kubernetes.default.svc
    namespace: mintoak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
